# Generated by Django 5.2.1 on 2025-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='producers/logos/', verbose_name='Логотип'),
        ),
    ]
