# Generated by Django 5.2.1 on 2025-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_producer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='producer/logos/', verbose_name='Логотип'),
        ),
    ]
