# Generated by Django 5.2.1 on 2025-05-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_alter_producer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='logo',
        ),
    ]
