# Generated by Django 5.2.1 on 2025-06-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_remove_producer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='producer_country',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='producer_description',
        ),
    ]
