# Generated by Django 5.2.1 on 2025-06-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_remove_producer_producer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
