# Generated by Django 5.2.1 on 2025-05-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255, verbose_name='Категорія')),
                ('button_icon', models.ImageField(blank=True, null=True, upload_to='assortment/category_icons_buttons/')),
                ('display_icon', models.ImageField(blank=True, null=True, upload_to='assortment/category_icons')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assortment_name', models.CharField(max_length=200, verbose_name='Назва продукту')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ціна продукту')),
                ('grams', models.IntegerField(blank=True, null=True, verbose_name='Грамовка продукту')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='assortment/posters/', verbose_name='Картинка продукту')),
                ('assortment_description', models.TextField(null=True, verbose_name='Опис продукту')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наявність продукту')),
                ('has_variants', models.BooleanField(default=False, verbose_name='Чи є варіанти продукту')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.producer', verbose_name='Назва виробника')),
                ('assortment_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assortment.category', verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['assortment_name'],
            },
        ),
        migrations.CreateModel(
            name='AssortmentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(verbose_name='Грамовка продукту')),
                ('price', models.FloatField(verbose_name='Ціна за грамовку')),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='assortment.assortment', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Варіант продукту',
                'verbose_name_plural': 'Варіанти продуктів',
                'ordering': ['grams'],
            },
        ),
    ]
