# Generated by Django 5.2.1 on 2025-05-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.producer', verbose_name='Назва виробника'),
        ),
    ]
