# Generated by Django 5.2.1 on 2025-05-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0003_subcategory_assortment_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи фільтрів')),
            ],
            options={
                'verbose_name': 'Група фільтрів',
                'verbose_name_plural': 'Групи фільтрів',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва опції')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assortment.filtergroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Опція фільтра',
                'verbose_name_plural': 'Опції фільтрів',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assortment',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products', to='assortment.filteroption', verbose_name='Фільтри'),
        ),
    ]
