# Generated by Django 5.2.1 on 2025-05-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0004_filtergroup_filteroption_assortment_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortment',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
