# Generated by Django 5.2.1 on 2025-05-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0005_remove_assortment_sub_category_delete_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filteroption',
            unique_together={('group', 'name')},
        ),
    ]
