# Generated by Django 5.2.1 on 2025-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0006_alter_filteroption_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна продукту'),
        ),
        migrations.AlterField(
            model_name='assortmentvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за грамовку'),
        ),
    ]
