# Generated by Django 5.2.1 on 2025-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0007_alter_assortment_price_alter_assortmentvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-20 00:00:00', verbose_name='Дата додавання'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assortment',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярність'),
        ),
    ]
