# Generated by Django 5.2.1 on 2025-05-20 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0008_assortment_created_at_assortment_popularity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, verbose_name='Відгук')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='assortment.assortment', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'assortment')},
            },
        ),
    ]
