# Generated by Django 5.2.1 on 2025-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва мітки')),
            ],
            options={
                'verbose_name': 'Мітка',
                'verbose_name_plural': 'Мітки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assortment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='assortment.tag', verbose_name='Мітки'),
        ),
    ]
