# Generated by Django 5.2.1 on 2025-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0011_remove_assortment_assortment_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='Акційний товар'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AddField(
            model_name='assortmentvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
    ]
