# Generated by Django 5.2.1 on 2025-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0012_assortment_is_discounted_assortment_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='poster',
            field=models.ImageField(upload_to='assortment/posters/', verbose_name='Картинка продукту'),
        ),
    ]
