# Generated by Django 5.2.1 on 2025-05-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0013_alter_assortment_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assortment/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assortment.assortment')),
            ],
        ),
    ]
