# Generated by Django 5.2.1 on 2025-05-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0015_delete_assortmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assortment/gallery/', verbose_name='Фото в галереї')),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assortment.assortment')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Галерея зображень',
            },
        ),
    ]
