# Generated by Django 5.2.1 on 2025-05-24 05:28

import assortment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0016_assortmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='assortment_categories',
            field=models.ManyToManyField(help_text='Оберіть одну або декілька категорій', related_name='assortments', to='assortment.category', verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='assortment_description',
            field=models.TextField(help_text='Короткий опис або інструкція', null=True, verbose_name='Опис продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='assortment_name',
            field=models.CharField(help_text='Наприклад: Кешʼю смажений, Фініки королівські', max_length=200, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='filters',
            field=models.ManyToManyField(blank=True, help_text='Оберіть відповідні фільтри для цього товару', related_name='products', to='assortment.filteroption', verbose_name='Фільтри'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='grams',
            field=models.IntegerField(blank=True, help_text='Вкажіть вагу у грамах, якщо товар без варіантів', null=True, verbose_name='Грамовка продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Відмітьте, якщо у товару є різні грамовки', verbose_name='Чи є варіанти продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Чи є товар у наявності', verbose_name='Наявність продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкажіть стару ціну, якщо товар акційний', max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='poster',
            field=models.ImageField(help_text='Головне зображення продукту', upload_to='assortment/posters/', validators=[assortment.validators.validate_image], verbose_name='Картинка продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Залишити порожнім, якщо товар має варіанти', max_digits=10, null=True, verbose_name='Ціна продукту'),
        ),
        migrations.AlterField(
            model_name='assortment',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Можна обрати декілька міток', related_name='products', to='assortment.tag', verbose_name='Мітки'),
        ),
        migrations.AlterField(
            model_name='assortmentimage',
            name='image',
            field=models.ImageField(upload_to='assortment/gallery/', validators=[assortment.validators.validate_image], verbose_name='Фото в галереї'),
        ),
    ]
