# Generated by Django 5.2.1 on 2025-05-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0017_alter_assortment_assortment_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_icon',
        ),
    ]
