# Generated by Django 5.2.1 on 2025-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0018_remove_category_display_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='drop_down_icon',
            field=models.ImageField(blank=True, null=True, upload_to='assortment/category_icons'),
        ),
    ]
