# Generated by Django 5.2.1 on 2025-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0019_category_drop_down_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='drop_down_icon_hover',
            field=models.ImageField(blank=True, null=True, upload_to='assortment/category_icons'),
        ),
    ]
