# Generated by Django 5.2.1 on 2025-05-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0020_category_drop_down_icon_hover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='drop_down_icon',
            new_name='button_icon_brown',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='button_icon',
            new_name='button_icon_white',
        ),
        migrations.RemoveField(
            model_name='category',
            name='drop_down_icon_hover',
        ),
    ]
