# Generated by Django 5.2.1 on 2025-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0022_alter_category_button_icon_brown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='button_icon_brown',
            field=models.ImageField(blank=True, null=True, upload_to='assortment/category_icons_brown/'),
        ),
    ]
