# Generated by Django 5.2.1 on 2025-05-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0024_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortment',
            name='is_discounted',
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='assortmentvariant',
            name='old_price',
        ),
    ]
