# Generated by Django 5.2.1 on 2025-06-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0025_remove_assortment_is_discounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='assortment/category_covers/', verbose_name='Обкладинка категорії'),
        ),
    ]
