# Generated by Django 5.2.1 on 2025-06-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0027_assortment_assortment_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortment',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
