# Generated by Django 5.2.1 on 2025-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
