# Generated by Django 5.2.1 on 2025-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationcode_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='last_sent_at',
            field=models.DateTimeField(),
        ),
    ]
