# Generated by Django 5.2.1 on 2025-05-24 03:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_verificationcode_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[accounts.validators.validate_ukrainian_phone]),
        ),
    ]
