# Generated by Django 5.1.5 on 2025-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('paid', 'Оплачено'), ('failed', 'Не вдалося')], default='pending', max_length=20),
        ),
    ]
