# Generated by Django 5.2.1 on 2025-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
